# Generated by Django 5.0.6 on 2025-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
