# Generated by Django 5.0.6 on 2025-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_firestation_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefighters',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firefighters',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
