# Generated by Django 5.0.6 on 2025-05-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_firefighters_contact_number_firefighters_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firetruck',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'In Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='ACTIVE', max_length=20),
        ),
    ]
